server:
  port: 9802

jwt: 
  secret: helloasdasdasdasdadfdfsdfsdfasdasdawdawdasdasdwdasdaw
  expiration: 120000
  header: Authorization
  
spring:
  application:
    name: gateway
    cloud:
    gateway:
      routes:
        - id: BANK
          uri: http://localhost:8080
          predicates:
            - Path=/bank/**
    discovery:
      enabled: true
      
  main:
    web-application-type: reactive
  
